import {Team} from './team';

export const TEAMS: Team[] = [
  {id: 0, name: 'Россия', flag: 'test'},
  {id: 1, name: 'Египет', flag: 'test'},
  {id: 2, name: 'Уругвай', flag: 'test'},
  {id: 3, name: 'Сауд. Аравия', flag: 'test'},
  {id: 4, name: 'Португалия', flag: 'test'},
  {id: 5, name: 'Испания', flag: 'test'},
  {id: 6, name: 'Иран', flag: 'test'},
  {id: 7, name: 'Марокко', flag: 'test'},
  {id: 8, name: 'Франция', flag: 'test'},
  {id: 9, name: 'Дания', flag: 'test'},
  {id: 10, name: 'Австралия', flag: 'test'},
  {id: 11, name: 'Перу', flag: 'test'},
  {id: 12, name: 'Хорватия', flag: 'test'},
  {id: 13, name: 'Исландия', flag: 'test'},
  {id: 14, name: 'Аргентина', flag: 'test'},
  {id: 15, name: 'Нигерия', flag: 'test'},
  {id: 16, name: 'Швейцария', flag: 'test'},
  {id: 17, name: 'Сербия', flag: 'test'},
  {id: 18, name: 'Бразилия', flag: 'test'},
  {id: 19, name: 'Коста-Рика', flag: 'test'},
  {id: 20, name: 'Германия', flag: 'test'},
  {id: 21, name: 'Швеция', flag: 'test'},
  {id: 22, name: 'Южная Корея', flag: 'test'},
  {id: 23, name: 'Мексика', flag: 'test'},
  {id: 24, name: 'Англия', flag: 'test'},
  {id: 25, name: 'Бельгия', flag: 'test'},
  {id: 26, name: 'Тунис', flag: 'test'},
  {id: 27, name: 'Панама', flag: 'test'},
  {id: 28, name: 'Польша', flag: 'test'},
  {id: 29, name: 'Колумбия', flag: 'test'},
  {id: 30, name: 'Япония', flag: 'test'},
  {id: 31, name: 'Сенегал', flag: 'test'},
];

