// import {Team} from './team';
//
// export const TEAMS: Team[] = [
//   {id: 0, name: 'Россия', points: 0, matches: 0},
//   {id: 1, name: 'Египет', points: 0, matches: 0},
//   {id: 2, name: 'Уругвай', points: 0, matches: 0},
//   {id: 3, name: 'Сауд. Аравия', points: 0, matches: 0},
//   {id: 4, name: 'Португалия', points: 0, matches: 0},
//   {id: 5, name: 'Испания', points: 0, matches: 0},
//   {id: 6, name: 'Иран', points: 0, matches: 0},
//   {id: 7, name: 'Марокко', points: 0, matches: 0},
//   {id: 8, name: 'Франция', points: 0, matches: 0},
//   {id: 9, name: 'Дания', points: 0, matches: 0},
//   {id: 10, name: 'Австралия', points: 0, matches: 0},
//   {id: 11, name: 'Перу', points: 0, matches: 0},
//   {id: 12, name: 'Хорватия', points: 0, matches: 0},
//   {id: 13, name: 'Исландия', points: 0, matches: 0},
//   {id: 14, name: 'Аргентина', points: 0, matches: 0},
//   {id: 15, name: 'Нигерия', points: 0, matches: 0},
//   {id: 16, name: 'Швейцария', points: 0, matches: 0},
//   {id: 17, name: 'Сербия', points: 0, matches: 0},
//   {id: 18, name: 'Бразилия', points: 0, matches: 0},
//   {id: 19, name: 'Коста-Рика', points: 0, matches: 0},
//   {id: 20, name: 'Германия', points: 0, matches: 0},
//   {id: 21, name: 'Швеция', points: 0, matches: 0},
//   {id: 22, name: 'Южная Корея', points: 0, matches: 0},
//   {id: 23, name: 'Мексика', points: 0, matches: 0},
//   {id: 24, name: 'Англия', points: 0, matches: 0},
//   {id: 25, name: 'Бельгия', points: 0, matches: 0},
//   {id: 26, name: 'Тунис', points: 0, matches: 0},
//   {id: 27, name: 'Панама', points: 0, matches: 0},
//   {id: 28, name: 'Польша', points: 0, matches: 0},
//   {id: 29, name: 'Колумбия', points: 0, matches: 0},
//   {id: 30, name: 'Япония', points: 0, matches: 0},
//   {id: 31, name: 'Сенегал', points: 0, matches: 0},
// ];
//
